//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Id { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public Nullable<int> IdTeacher { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<double> Scores1 { get; set; }
        public Nullable<double> Scores2 { get; set; }
        public Nullable<double> Examscores { get; set; }
        public Nullable<double> Point { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
