//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string gender { get; set; }
        public string date { get; set; }
        public string sothich { get; set; }
        public string quoctich { get; set; }
    }
}
