//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Marks = new HashSet<Marks>();
            this.Marks1 = new HashSet<Marks>();
        }
    
        public int IdTeacher { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string TeacherName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IdClass { get; set; }
        public Nullable<int> IdFaculty { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual ClassRoom ClassRoom1 { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Faculty Faculty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marks> Marks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marks> Marks1 { get; set; }
    }
}
